goog.provide('riemann_grid.client.routes');
goog.require('cljs.core');
goog.require('jayq.util');
goog.require('jayq.core');
goog.require('jayq.util');
goog.require('jayq.core');
goog.require('riemann_grid.client.controller');
goog.require('goog.events');
goog.require('snout.core');
console.log([cljs.core.str("starting up with query: "),cljs.core.str(cljs.core.deref.call(null,riemann_grid.client.controller.stored_query))].join(''));
riemann_grid.client.controller.grid.call(null,"true");
